import 'package:flutter/material.dart';
import 'package:food_recipie_app/food/meals.dart';
import 'package:food_recipie_app/food/recipie.dart';

const DUMMY_CATEGORIES = const [
  Category(
      id: 'c1',
      title: 'Masala Dosa',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.vegrecipesofindia.com%2Fwp-content%2Fuploads%2F2021%2F06%2Fmasala-dosa-2.jpg&imgrefurl=https%3A%2F%2Fwww.vegrecipesofindia.com%2Fmasala-dosa-recipe-how-to-make-masala-dosa-recipe%2F&tbnid=tEoaa0-EJyDHhM&vet=12ahUKEwjOtMXs3pX4AhUejdgFHfFkBZoQMygDegUIARD_AQ..i&docid=jYC96f5v0I4fiM&w=600&h=600&q=masala%20dosa&ved=2ahUKEwjOtMXs3pX4AhUejdgFHfFkBZoQMygDegUIARD_AQ'),
  Category(
      id: 'c2',
      title: 'Biryani',
      imageUrl:
          '.indianhealthyrecipes.com%2Fhyderabadi-biryani-recipe%2F&psig=AOvVaw09d0mSr6UP8O9uS1Tlw9tJ&ust=1654498941005000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCNjuyZXglfgCFQAAAAAdAAAAABAD'),
  Category(
      id: 'c3',
      title: 'Chole bhature',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.secondrecipe.com%2Fwp-content%2Fuploads%2F2016%2F04%2Fchanna-bhatura-500x500.jpg&imgrefurl=https%3A%2F%2Fwww.secondrecipe.com%2Fpunjabi-chole-channa-masala%2F&tbnid=C7-8JHr37aAhzM&vet=12ahUKEwiXxsOb35X4AhUri9gFHd28C44QMygAegUIARDyAQ..i&docid=lPMrqQR4WJXitM&w=500&h=500&q=chole%20bhature&ved=2ahUKEwiXxsOb35X4AhUri9gFHd28C44QMygAegUIARDyAQ'),
  Category(
      id: 'c4',
      title: 'Samosa',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.cubesnjuliennes.com%2Fwp-content%2Fuploads%2F2020%2F08%2FBest-Mutton-Keema-Samosa-Recipe-1.jpg&imgrefurl=https%3A%2F%2Fwww.cubesnjuliennes.com%2Fkeema-samosa-html%2F&tbnid=r0_IqrImRf6RPM&vet=12ahUKEwj0uvm235X4AhX6jtgFHeGaDoIQMygCegUIARCCAg..i&docid=Gcr6V-wPmpWUBM&w=1200&h=1201&q=samosa&ved=2ahUKEwj0uvm235X4AhX6jtgFHeGaDoIQMygCegUIARCCAg'),
  Category(
      id: 'c5',
      title: 'paneer Tikka',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.carveyourcraving.com%2Fwp-content%2Fuploads%2F2021%2F10%2Fpaneer-tikka-skewers.jpg&imgrefurl=https%3A%2F%2Fwww.carveyourcraving.com%2Fpaneer-tikka-oven%2F&tbnid=RWQQbsbAgtEQGM&vet=12ahUKEwig2djK35X4AhUritgFHdfZAzoQMygDegUIARCFAg..i&docid=gLYWPd9R7GmksM&w=1200&h=1200&q=panner%20tikka&ved=2ahUKEwig2djK35X4AhUritgFHdfZAzoQMygDegUIARCFAg'),
  Category(
      id: 'c6',
      title: 'Mutton gravy',
      imageUrl:
          'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUqhvooXRd0M&psig=AOvVaw1-iAgutHa4YiiYGp-6t6w0&ust=1654499141611000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLjK-PXglfgCFQAAAAAdAAAAABAD'),
  Category(
      id: 'c7',
      title: 'Paratha',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.apartmenttherapy.info%2Fimage%2Fupload%2Ff_jpg%2Cq_auto%3Aeco%2Cc_fill%2Cg_auto%2Cw_1500%2Car_4%3A3%2Fk%252FPhoto%252FRecipe%2520Ramp%2520Up%252F2022-02-Paratha%252Fparatha-stacked-top_view&imgrefurl=https%3A%2F%2Fwww.thekitchn.com%2Fparathas-recipe-23280232&tbnid=swZk1TJn5rMCBM&vet=12ahUKEwj1keOH4JX4AhWmgGMGHQRNCUYQMygBegUIARCEAg..i&docid=ijYjx8b3B6lprM&w=1500&h=1125&q=paratha&ved=2ahUKEwj1keOH4JX4AhWmgGMGHQRNCUYQMygBegUIARCEAg'),
  Category(
      id: 'c8',
      title: 'Vada Pav',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.cookwithmanali.com%2Fwp-content%2Fuploads%2F2018%2F04%2FVada-Pav-500x500.jpg&imgrefurl=https%3A%2F%2Fwww.cookwithmanali.com%2Fvada-pav%2F&tbnid=smd2HrRVSvU72M&vet=12ahUKEwiZkZ2d4JX4AhUc_jgGHdF-C0oQMygAegUIARD4AQ..i&docid=B3wPtD5x-ZzOJM&w=660&h=660&q=vada%20pav&ved=2ahUKEwiZkZ2d4JX4AhUc_jgGHdF-C0oQMygAegUIARD4AQ'),
  Category(
      id: 'c9',
      title: 'Chat',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F52727664.cms%3Fwidth%3D1200%26height%3D900&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fdahi-papdi-chaat%2Frs52727664.cms&tbnid=cO-SXJR7TS465M&vet=12ahUKEwim5uq24JX4AhVY_DgGHZVIDSsQMygBegUIARDxAQ..i&docid=yPGSEJewIXztLM&w=1200&h=900&q=chaat&ved=2ahUKEwim5uq24JX4AhVY_DgGHZVIDSsQMygBegUIARDxAQ'),
  Category(
      id: 'c10',
      title: 'jalebi',
      imageUrl:
          'https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F53099699.cms%3Fwidth%3D1200%26height%3D900&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fjalebi%2Frs53099699.cms&tbnid=LN2FGR0B9xtC3M&vet=12ahUKEwjwldrQ4JX4AhUDidgFHezbDbAQMygAegUIARD8AQ..i&docid=kKIHwCEognc1PM&w=1200&h=900&q=jalebi&ved=2ahUKEwjwldrQ4JX4AhUDidgFHezbDbAQMygAegUIARD8AQ'),
];

const DUMMY_MEALS = [
  Meal(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'Masala Dosa',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.vegrecipesofindia.com%2Fwp-content%2Fuploads%2F2021%2F06%2Fmasala-dosa-2.jpg&imgrefurl=https%3A%2F%2Fwww.vegrecipesofindia.com%2Fmasala-dosa-recipe-how-to-make-masala-dosa-recipe%2F&tbnid=tEoaa0-EJyDHhM&vet=12ahUKEwjOtMXs3pX4AhUejdgFHfFkBZoQMygDegUIARD_AQ..i&docid=jYC96f5v0I4fiM&w=600&h=600&q=masala%20dosa&ved=2ahUKEwjOtMXs3pX4AhUejdgFHfFkBZoQMygDegUIARD_AQ',
    duration: 20,
    ingredients: [
      'Oil',
      '3 Potatoes',
      '1 Onion',
      '5 Curry Leaves',
      '2 Green Chilies',
      '1 Tablespoon Cilantro',
      '¼ Teaspoon Mustard Seeds',
      '¼ Teaspoon Chana Dal',
      'Turmeric Powder',
      '¼ Cup Green Peas',
      '3 Banana Leaves',
      'Pepper',
      'Lemon Juice'
    ],
    steps: [
      'Boil the potatoes and mash them perfectly',
      'Take a pan and heat oil init',
      'Add mustard seeds, chana dal and curry leaves. Let them splutter and add green chilies to it',
      'Add sliced onions and let it saute for about 2 minutes',
      'Add mashed potatoes and green peas to the mixture and cook for 5 minutes. Add water if required',
      'Add the chopped cilantro on the top',
      'Place the dosa griddle on high flame and pour spoonful of dosa batter on it',
      'Spread it using the back of the spoon by making concentric circular motion',
      'Add few drops of oil to it',
      'Once the sides of the dosa are cooked or turned to golden brown, flip the dosa and cook the other side too',
      'Flip the dosa after 30 seconds and place the above potato mixture in the center of the dosa',
      'Cover the masala with dosa as shown in the picture',
      'The Tasty Masala Dosa is ready to serve',
      'Serve it with coconut chutney or even with Udipi Samabar. Have breakfast like a king and lunch like a prince. Know the Benefits of Breakfast.'
    ],
    isVegeterian: true,
    isNonVegterian: false,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Biryani',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl:
        'indianhealthyrecipes.com%2Fhyderabadi-biryani-recipe%2F&psig=AOvVaw09d0mSr6UP88O9uS1Tlw9tJ&ust=1654498941005000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCNjuyZXglfgCFQAAAAAdAAAAABAD',
    duration: 120,
    ingredients: [
      '600 gm basmati rice',
      '4 tablespoon mint leaves',
      'salt as required',
      '2 teaspoon coriander powder',
      '1 tablespoon garlic paste',
      '2 tablespoon tomato puree',
      '400 gm white onion',
      '8 green cardamom',
      '1 tablespoon milk',
      '1 kilograms chicken thighs',
      '1 teaspoon garam masala powder',
      '2 pinches saffron',
      '1 tablespoon ginger paste',
      '4 green chilli',
      '300 gm tomato',
      '2 teaspoon cumin seeds',
      '6 tablespoon refined oil',
      '1/2 teaspoon chilli powder',
      '6 tablespoon plain greek yogurt',
      '1 teaspoon powdered turmeric'
    ],
    steps: [
      'To prepare this mouth-watering biryani recipe, you have to marinate the chicken. For the same, take a large bowl and add Greek yoghurt in it along with turmeric, chili powder along with salt as per your taste in a small bowl. Mix well using a spoon and then, add the chicken thighs in the mixture and rub with this mixture. Keep aside for about 20-30 minutes, so that the yogurt mixture is properly absorbed by the chicken. Also, soak saffron in the milk to make saffron milk and keep aside.',
      'In the meanwhile, pour refined oil in a deep-bottomed pan, keeping it on medium flame. Add cumin seeds and green cardamom in it and saute for about 2 minutes. Once done, immediately add the sliced onion and fry for 2-3 minutes straight. Make sure you dont burn it, so when the onion starts to get brown in color, add tomatoes and tomato puree and fry for another 5 minutes.',
      'Next, add the slit green chilies to the mixture along with ginger-garlic paste, frying the mixture yet again for a minute. Then, add coriander powder and turn the flame to medium-low while stirring and cooking the masala. Quickly, add the marinated chicken and mix for a while so that the ingredients absorb the juices properly.',
      'Turn the flame to medium again and heat-through for about 5-6 minutes only to turn it over to low heat. Cover with a lid and let simmer for 5 minutes. Make sure to keep stirring during the entire process, else the chicken might stick to the bottom, eventually ending up burnt. You can add little water, if you find the consistency too thick.',
      'Once done, turn off the flame and add half of the boiled rice in the pan and keep the rest aside until required. Sprinkle milk soaked saffron along with garam masala, mint and coriander leaves. Put the remaining rice over this layer and garnish with the same mentioned four ingredients.',
      'Lastly, cover the lid, turn the flame to low medium and let the rice cook for about 5 minutes. Once done, put it off and let the biryani stay covered for about another 10 minutes. Serve hot, along with raita or any chutney of your choice.',
      ' If your cooked rice has turned sticky, spread it on a plate and leave them for 5 minutes. The rice will be sperate and beautiful again. 2. Freshly pound spices bring out the best taste in Biryani.'
    ],
    isVegeterian: false,
    isNonVegterian: true,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c3',
    ],
    title: 'Chole bhature',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.secondrecipe.com%2Fwp-content%2Fuploads%2F2016%2F04%2Fchanna-bhatura-500x500.jpg&imgrefurl=https%3A%2F%2Fwww.secondrecipe.com%2Fpunjabi-chole-channa-masala%2F&tbnid=C7-8JHr37aAhzM&vet=12ahUKEwiXxsOb35X4AhUri9gFHd28C44QMygAegUIARDyAQ..i&docid=lPMrqQR4WJXitM&w=500&h=500&q=chole%20bhature&ved=2ahUKEwiXxsOb35X4AhUri9gFHd28C44QMygAegUIARDyAQ',
    duration: 45,
    ingredients: [
      '2 cup chickpeas (channas)',
      '2 tsp oil',
      '1 Bbay leaf (tej patta)',
      '1 Cinnamon stick (dalchini)',
      '3-4 Cloves (laung)',
      '1 tsp whole pepper corns (sabut kali mirch)',
      '3 Green cardamom (choti elaichi)',
      '2 Black cardamom (badi elaichi)',
      '1 tsp rurmeric powder (haldi)',
      '1 tsp chili powder (lal mirch powder)',
      '1 tsp coriander powder (dhaniya powder)',
      '1 tsp cumin powder (zeera powder)',
      '1 tsp cumin seeds (zeera)',
      '1/2 tsp asafoetida (heeng)',
      'to taste salt',
      '1 cup onions, chopped',
      '1 cup tomatoes, chopped',
      '1 tsp ginger, chopped',
      '1 tsp garlic, chopped',
      '1 tsp ajwain',
      '1 tsp lime juice',
      '1 green chili, chopped',
      '1 Tea bag',
      '1 tbsp butter',
      'For the bhaturas-2 cups maida (refined flour)',
      '1/2 tsp yeast (dissolved for 10 minutes in luke warm water)',
      '1/2 cup whole wheat flour',
      'A pinch of salt',
      'Water (to knead)',
      'Oil (for frying)',
    ],
    steps: [
      'In a pan add oil, bay leaf, cinnamon, cumin seeds, cloves, whole pepper corns, green and black cardamom.',
      'After it gets brown add chopped onions and saute it. Now add chopped ginger and garlic.',
      'Followed by turmeric, chili powder, coriander powder, cumin powder, asafoetida and salt, fry the ingredients together well.',
      'For de glazing the pan add a little water.',
      'Now add the chole (soaked overnight and pressure cooked) to the masala.',
      'After stirring well add tomatoes, little sugar and salt to the chole.',
      'Now add ajwain, chopped green chilies and water for the base.',
      'To get the color in the chole, add a tea bag to the masala.',
      'Simmer the chole gently for an hour and cover it.',
      'Add lime juice and a dollop of butter to it.',
      'Garnish the chole with coriander and butter and serve them hot with bhaturas.',
      'Knead the whole wheat flour, maida and salt together with adequate amount of water.',
      'Sprinkle the yeast on top. Leave it for 2-3 hours for the yeast to work.',
      'Divide it into equal portions. Roll out in an oval or round shape.',
      'Deep fry till golden brown, like a puri',
      'Serve.'
    ],
    isVegeterian: true,
    isNonVegterian: false,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Samosa',
    affordability: Affordability.Affordable,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.cubesnjuliennes.com%2Fwp-content%2Fuploads%2F2020%2F08%2FBest-Mutton-Keema-Samosa-Recipe-1.jpg&imgrefurl=https%3A%2F%2Fwww.cubesnjuliennes.com%2Fkeema-samosa-html%2F&tbnid=r0_IqrImRf6RPM&vet=12ahUKEwj0uvm235X4AhX6jtgFHeGaDoIQMygCegUIARCCAg..i&docid=Gcr6V-wPmpWUBM&w=1200&h=1201&q=samosa&ved=2ahUKEwj0uvm235X4AhX6jtgFHeGaDoIQMygCegUIARCCAg',
    duration: 30,
    ingredients: [
      '4 cup all purpose flour',
      '1 teaspoon garam masala powder',
      '4 tablespoon ghee',
      '4 boiled potato',
      '2 green chilli',
      '5 cloves garlic',
      '2 teaspoon red chilli powder',
      '2 teaspoon dry mango powder',
      '1 teaspoon turmeric',
      '2 teaspoon coriander powder',
      '2 teaspoon carom seeds',
      'salt as required',
      '2 cup peas',
      '2 inch ginger',
      '2 teaspoon cumin seeds',
      'black pepper as required',
      '1 cup chopped coriander leaves',
      '2 cup refined oil',
    ],
    steps: [
      'To prepare this delicious dish, prepare the stuffing for samosa by placing a pan on medium flame. Add oil in it and when the oil is hot enough, add cumin seeds in it and let them crackle. Immediately, add garlic, ginger and green chilli paste and salt as per your taste',
      'Then, combine dry mango powder, coriander powder, coriander leaves, garam masala along with turmeric and red chilli powder. Keep stirring the mixture the whole while. Next, add boiled potato and stir yet again. With the help of the back of a spoon, mash the entire mixture altogether.',
      'Now to prepare the dough, take a dough kneading plate and combine all-purpose flour along with cumin seeds, salt and black pepper according to your taste. Then, add ghee and start kneading. Make sure the dough turns out to be somewhat firm in its texture. Cover the dough with a muslin cloth and keep aside for about half an hour.',
      'Once done, roll out few small-sized balls from the dough. Flatten them further with the help of your palms and then with a rolling pin. Give them a round shape and cut it in half. Now dipping your hands in water, fold the edges of the semi-circle in order to give it a cone shape.',
      'Take the filling and stuff the prepared mixture in it. Seal the ends properly by pressing the edges lightly with your fingers. Then, heat oil in a pan and deep fry the samosas until they turn golden brown and crispy enough. Serve with tomato ketchup and green chutney. Enjoy it as a tea-time snack.',
      'To make Samosa the right way, make sure you knead a tight or stiff dough as the soft dough will not yield best results. 2. Before kneading the dough, keep it in mind that you do not need to overwork on it and mix the oil with flour at least 5-6 times. This will ensure you have crispy Samosas. 3. Another thing you need to understand is that the Samosa dough should be used after resting for a bit. You should keep aside the dough for at least 40-60 minutes. 4. While rolling the dough ball, keep it thin and do not use any flour in it. You can use a little oil to roll the ball evenly. 5. While frying the Samosa, it should be kept in mind that never ever keep the flame on high. This way your samosa will not be cooked till inside and the outside will be soft. Keep your flame to low irrespective of how much time it is taking to fry. This will also ensure that your samosas are blisters free.',
      'Serve.'
    ],
    isVegeterian: true,
    isNonVegterian: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c5',
    ],
    title: 'Paneer Tikka',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Hard,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.carveyourcraving.com%2Fwp-content%2Fuploads%2F2021%2F10%2Fpaneer-tikka-skewers.jpg&imgrefurl=https%3A%2F%2Fwww.carveyourcraving.com%2Fpaneer-tikka-oven%2F&tbnid=RWQQbsbAgtEQGM&vet=12ahUKEwig2djK35X4AhUritgFHdfZAzoQMygDegUIARCFAg..i&docid=gLYWPd9R7GmksM&w=1200&h=1200&q=panner%20tikka&ved=2ahUKEwig2djK35X4AhUritgFHdfZAzoQMygDegUIARCFAg',
    duration: 30,
    ingredients: [
      '½ cup curd / yogurt, thick',
      '½ tsp turmeric / haldi',
      '1 tsp kashmiri red chilli powder / lal mirch powder'
          '½ tsp coriander powder / daniya powder',
      '¼ tsp cumin powder / jeera powder',
      '½ tsp garam masala',
      '½ tsp kasuri methi / dry fenugreek leaves, crushed',
      '½ tsp chaat masala',
      '1 tsp ginger - garlic paste',
      '¼ tsp ajwain / carom seeds',
      '2 tsp besan / gram flour, dry roasted',
      '1 tbsp lemon juice',
      'salt to taste',
      '3 tsp oil',
      '½ onions, petals',
      '½ capsicum, red & green, cubed',
      '5 cubes paneer / cottage cheese'
    ],
    steps: [
      'firstly, take ½ cup thick curd / yogurt.',
      'further add in all the spices along with salt.',
      'mix till all the spices are combined well with curd.',
      'now add ½ onion petals, ½ cubed capsicum (red & green) and 5 cubes paneer.',
      'also add 1 tsp of oil.',
      'mix gently till all the vegetables are coated well.',
      'furthermore, to marinate, cover and refrigerate for 30 minutes.',
      'after marination, insert the marinated paneer, capsicum and onions into wooden skewers.',
      'further, roast it on a hot tawa or grill in oven or tandoor.',
      'finally, sprinkle some chaat masala and serve paneer tikka immediately.'
    ],
    isVegeterian: true,
    isNonVegterian: false,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
    ],
    title: 'Kolhapuri mutton',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl:
        'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUqhvooXRd0M&psig=AOvVaw1-iAgutHa4YiiYGp-6t6w0&ust=1654499141611000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLjK-PXglfgCFQAAAAAdAAAAABAD',
    duration: 240,
    ingredients: [
      ' 1/2 kg Mutton pieces',
      '2 tsps ginger-garlic paste',
      '1 tsp refined oil',
      '1/4 tsp turmeric powder',
      '1 tsp salt',
      '2 Onions Big -chopped',
      '1/2 cup coconut (7 tbsp) grated',
      '1 tbsp refined oil',
      '1 1/2 tsps Coriander seeds',
      '1/2 tsp cumin seeds',
      '1 1/2 tsps sesame seeds',
      '3 tsps poppy seeds',
      '8 chillies red',
      '1 clove',
      '2 Onions -chopped fine',
      '2 tsps refined oil',
      '3/4 tsp salt',
      'coriander leaves few',
      'water required'
    ],
    steps: [
      'Mix all the marination ex.ginger-garlic paste and salt and evenly rub the marination on mutton pieces and keep this in fridge for an hour atleast.',
      'To prepare the Kolhapuri Masala:Heat oil in a kadai,add coriander seeds,cumin seeds,sesame seeds,poppy seeds,red chillies,clove and saute this till the seeds begin to crackle.Add the onions and saute this till golden brown.Finally add the grated coconut and saute for 2-3 mins.Turn off the flame.Leave this aside for 15 mins and grind this into a fine paste with 50ml water.Keep this aside.',
      'Heat oil in a pan and saute the finely chopped onions on medium heat till it turns golden brown.',
      'Add the marinated mutton pieces,salt and coriander leaves and saute till oil separates from the mixture.Add 2 tbsp water and stir tilloil floats on top.(repeat this 3-4 times till the mutton is 3/4th cooked).',
      'Add the kolhapuri masala paste and saute till oil separates on top again.Add 2 cups water and bring it to boil.',
      'Then,cover and simmer(stirring constantly) till the mutton is done.Turn off the flame.',
      'Garnish with coriander leaves and Serve this delicious mutton curry hot with rice or Indian bread of ur choice.',
    ],
    isVegeterian: false,
    isNonVegterian: true,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Paratha',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.apartmenttherapy.info%2Fimage%2Fupload%2Ff_jpg%2Cq_auto%3Aeco%2Cc_fill%2Cg_auto%2Cw_1500%2Car_4%3A3%2Fk%252FPhoto%252FRecipe%2520Ramp%2520Up%252F2022-02-Paratha%252Fparatha-stacked-top_view&imgrefurl=https%3A%2F%2Fwww.thekitchn.com%2Fparathas-recipe-23280232&tbnid=swZk1TJn5rMCBM&vet=12ahUKEwj1keOH4JX4AhWmgGMGHQRNCUYQMygBegUIARCEAg..i&docid=ijYjx8b3B6lprM&w=1500&h=1125&q=paratha&ved=2ahUKEwj1keOH4JX4AhWmgGMGHQRNCUYQMygBegUIARCEAg',
    duration: 20,
    ingredients: [
      '2 Cups Kuttu ka Atta',
      '1 Large Potato (peeled, mashed smooth), boiled',
      '1 tsp Rock salt',
      'Too knead Water',
      'For frying Ghee',
      'Fpr dusting Dry flour',
      '1 Tbsp Coriander leaves',
    ],
    steps: [
      'Mix together the mashed potatoes, rock salt, chilli powder, coriander leaves, green chillies.',
      'Knead the dough as for a normal parantha',
      'Make flat rounds and pinch the edges to about 1/3 way towards the centre, to form a sort of a cup',
      'Take some filling and place in the centre of the cup.',
      'Wet the edges and bring together to enclose the filling. Pinch to seal.',
      'Roll out as thinly as you can without tearing.',
      'Fry the paranthas till crisp and dark on both sides.',
      'Serve hot.'
    ],
    isVegeterian: true,
    isNonVegterian: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Vada Pav',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.cookwithmanali.com%2Fwp-content%2Fuploads%2F2018%2F04%2FVada-Pav-500x500.jpg&imgrefurl=https%3A%2F%2Fwww.cookwithmanali.com%2Fvada-pav%2F&tbnid=smd2HrRVSvU72M&vet=12ahUKEwiZkZ2d4JX4AhUc_jgGHdF-C0oQMygAegUIARD4AQ..i&docid=B3wPtD5x-ZzOJM&w=660&h=660&q=vada%20pav&ved=2ahUKEwiZkZ2d4JX4AhUc_jgGHdF-C0oQMygAegUIARD4AQ',
    duration: 35,
    ingredients: [
      '2 Tbsp oil',
      '1/4 tsp hing',
      '1 tsp mustard seeds',
      '2 tsp saunf',
      '1 onion',
      '2 tsp green chilli - garlic paste',
      '2 nos potato, boiled',
      '1 tsp turmeric powder',
      '1 tsp salt',
      '2 tsp red chilli powder',
      '2 tsp coriander leaves',
      '2 tsp lemon juice',
      '9 garlic cloves',
      '5 nos red chilli whole',
      '2 tsp white sesame seeds',
      '1 cup dessicated coconut',
      '2 tsp peanuts, roasted',
      '1/2 tsp salt',
      '1/2 tsp red chilli powder',
      '1/2 tsp tamarind',
      '1 cup besan',
      '1/4 cup soda',
      '1 tsp salt',
      '1 tsp red chilli powder',
      '4 Green chillies'
    ],
    steps: [
      'Take oil in a pan, put hing, mustard seeds and saunf. Roast together.',
      'Add onion and Green chilli-garlic paste and saute well.',
      'Now add boiled potatoes, turmeric powder, aa tsp of salt, 2 tsp of red chilli powder and coriander leaves.',
      'Mix them well and add lemon juice. Saute to make a paste',
      'Put oil in a pan and add garlic along with red chilli whole, white sesame seeds and desiccated coconut.',
      'Mix them well and add roasted peanuts and half a tsp each of salt and red chilli powder. Mix well.',
      'Now add tamarind and grind all the ingredients together to get a paste.',
      'Next, take a bowl and add besan, soda, a tsp each of salt and red chilli powder.',
      'Put some water and mix thoroughly to make a besan mix.',
      'Take the prepared masala paste and make small ball of it.',
      'Dip the balls completely in to the besan mix and deep fry in the pan.',
      'Fry till golden brown.',
      'Put some green chillies in the pan to fry for a while.',
      'Take buns and put green chutney, masala paste and the fried masala pakodas between them.',
      'Serve with the garnishing of fried green chillies on top of it.'
    ],
    isVegeterian: true,
    isNonVegterian: false,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Chat',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F52727664.cms%3Fwidth%3D1200%26height%3D900&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fdahi-papdi-chaat%2Frs52727664.cms&tbnid=cO-SXJR7TS465M&vet=12ahUKEwim5uq24JX4AhVY_DgGHZVIDSsQMygBegUIARDxAQ..i&docid=yPGSEJewIXztLM&w=1200&h=900&q=chaat&ved=2ahUKEwim5uq24JX4AhVY_DgGHZVIDSsQMygBegUIARDxAQ',
    duration: 45,
    ingredients: [
      '1 cup all-purpose flour',
      '4 tablespoons ghee',
      '1 teaspoon onion seeds',
      '1 tsp Kosher salt',
      'Water',
      'Vegetable oil, canola, or sunflower oil, to deep fry',
      'For the Toppings',
      '5 large potatoes',
      '1 15 oz can chickpeas, drained and rinsed',
      'Kosher salt, to taste',
      'For Assembly and Serving',
      '2 cups fresh yogurt, whisked until smooth',
      '2 red onions, finely chopped',
      '2 large tomatoes, finely chopped',
      '1 cup tamarind chutney',
      '1 cup mint-coriander chutney',
      '2 cups fine sev or gram flour',
      '2 teaspoons red chili powder',
      '2 tablespoons cumin seeds, gently roasted and ground',
      '3 teaspoons powdered black rock salt',
      'Garnish: 1/4 cup fresh coriander leaves, finely chopped'
    ],
    steps: [
      'Gather the dough ingredients. Mix the flour, ghee, onion seeds, and salt.',
      'Add water, a spoonful at a time, and knead to get a firm, smooth dough.',
      'Cover dough with a damp cloth, and allow it to rest for 20 minutes.',
      'After the dough has rested, divide it into equal-sized balls. Roll the dough balls between your palms until smooth.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isVegeterian: false,
    isNonVegterian: true,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c10',
    ],
    title: 'Jalebi',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.toiimg.com%2Fthumb%2F53099699.cms%3Fwidth%3D1200%26height%3D900&imgrefurl=https%3A%2F%2Frecipes.timesofindia.com%2Frecipes%2Fjalebi%2Frs53099699.cms&tbnid=LN2FGR0B9xtC3M&vet=12ahUKEwjwldrQ4JX4AhUDidgFHezbDbAQMygAegUIARD8AQ..i&docid=kKIHwCEognc1PM&w=1200&h=900&q=jalebi&ved=2ahUKEwjwldrQ4JX4AhUDidgFHezbDbAQMygAegUIARD8AQ',
    duration: 30,
    ingredients: [
      '3 cup all purpose flour',
      '2 cup hung curd',
      '1/2 cup ghee',
      '3 cup sugar',
      '5 strand saffron',
      '1/2 teaspoon powdered green cardamom',
      '1/2 cup corn flour',
      '1 1/2 pinch baking soda',
      '2 cup sunflower oil',
      '3 cup water',
      '4 drops rose essence',
      '1/2 teaspoon edible food color'
    ],
    steps: [
      'For making this easy dessert recipe, mix all-purpose flour, cornflour and baking soda in a bowl. Now, add ghee and orange food colour in the above mixture. To make a thick batter, add curd and water. Mix well until it is thick but has a pouring consistency. Keep it aside for 8 hours or overnight. 8-10 hours. To make the sugar syrup, heat water in a pan over medium flame. Add sugar and mix until fully dissolved. Simmer the syrup until it attains one string consistency. Add saffron, cardamom powder and rose essence. Stir well.',
      'Now, heat oil in a pan over medium flame for deep frying. Fill the jalebi batter in a muslin cloth and pierce a small hole in the cloth. Squeeze the muslin cloth to make concentric circles. Move from inside to outside to make perfect circles. Fry till jalebis are crisp and golden.',
      'Soak the jalebis in sugar syrup for 2-3 minutes. Ensure that the sugar syrup is warm and not very hot. Now remove from the syrup and place on a tray lined with butter paper or foil. Decorate with silver foil and serve the jalebis hot, warm or at room temperature with creamy Rabri.',
    ],
    isVegeterian: true,
    isNonVegterian: false,
  ),
];
